version: '3'

services:
  # app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db

  db:
    image: postgres:10.5
    container_name: postgres_db
    env_file:
      - path: ./.env
    ports:
      - "5432:5432"
